name: Analysis-Python

on:
  pull_request:
    branches: [main, master, develop]
    paths: '**.py'
  push:
    branches: [main, master, develop]
    paths: '**.py'


jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install ruff
      - run: ruff check $(git ls-files '*.py')

  mypy:
    name: MyPy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install mypy
      - run: mypy $(git ls-files '*.py') --config-file .mypy.ini
